### ISSUE TITLE
The `az acr build` command throws `TypeError: 'NoneType' object is not callable` exception

### ISSUE THREAD

**Issue by xenatisch** [Azure/azure-cli#18875]
**Resource Provider**
Azure CLI, running:

```
az acr build
```

**Description of Feature or Work Requested**
Trying to build the container in Azure DevOps pipeline for deployment. The job fails on running the command with the following Python exception from the CLI:

```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/build.py", line 109, in acr_build
    variant=platform_variant
TypeError: 'NoneType' object is not callable
To open an issue, please run: 'az feedback'
##[error]Script failed with exit code: 1
/usr/bin/az account clear
Finishing: Azure CLI - ACR remote build
```

**Target Date**
Immediate deployment - business critical issue.

It's a business critical issue for us, so I'm happy to escalate as a priority level 1 if needed.

Agent job:

```
Pool: Azure Pipelines
Image: ubuntu-20.04
Agent: Hosted Agent
Started: Today at 10:49
Duration: 11s
```

Build initialisation:
```
Starting: Azure CLI - ACR remote build
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.1.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
azure-cli                         2.26.0 *

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy

core                              2.26.0 *
telemetry                          1.0.6

Extensions:
azure-devops                      0.18.0

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.6.10 (default, Jul  2 2021, 06:40:29) 
[GCC 9.3.0]
```

**Comment by yonzhan** [comment]
route to service team

**Comment by wase90168** [comment]
I am experiencing the same issue with the command `az acr run ...` .

<details open>
<summary>Issue details...</summary>
<br>
**Command Name**
`az acr run`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/run.py", line 93, in acr_run
    variant=platform_variant
TypeError: 'NoneType' object is not callable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr run --cmd {} --registry {} {}`

## Expected Behavior

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.5

```



</details>

**Comment by xenatisch** [comment]
Update: 

I've changed my build command in Azure DevOps pipeline to the following:

```
az upgrade --yes; az acr build -r $(ContainerRegistry-Name) -t $(ContainerRegistry-Name).azurecr.io/greenhouse-server:latest-$(Build.SourceBranchName) -t $(ContainerRegistry-Name).azurecr.io/greenhouse-server:$(Build.BuildId)-$(Build.SourceBranchName) -g $(ContainerRegistry-ResourceGroup) .
```

It does seem to upgrade, but then it fails with the same exception.

**Comment by kbenchaaboun** [comment]
Same issue on our side with the 'az acr build'

Any update ? 

<img width="635" alt="Screenshot 2021-07-15 at 16 11 22" src="https://user-images.githubusercontent.com/14924329/125802414-d4113c75-6b8d-42bf-8287-dd4fc8f5f13a.png">

**Comment by marcin-vt** [comment]
Upgrading to 2.26.1 on my vm (ubuntu 20.04) solved the problem, however azure devops pipeline agent (ubuntu 18.04) won't upgrade (azure-cli is already the newest version (2.26.0-1~bionic)).

**Comment by JotaP** [comment]
Same here, we have all our Github action pipelines failing... we desperately need a fix for this.

**Comment by xenatisch** [comment]
@marcin-vt yeah, it won't work on the pipeline. There is another workaround, but it'll be messy @JotaP. You can build directly using `docker build`, then log in and push the built image into the registry.

Not very feasible if you have several pipelines for different things, connected to different branches like we do. It'll take a day to update and test them all.

**Comment by JotaP** [comment]
> @marcin-vt yeah, it won't work on the pipeline. There is another workaround, but it'll be messy @JotaP. You can build directly using `docker build`, then log in and push the built image into the registry.
> 
> Not very feasible if you have several pipelines for different things, connected to different branches like we do. It'll take a day to update and test them all.

Thanks for the workaround but sadly enough it's a big mess for us as we have a lot of different pipelines and automated stuff around them. Anyways, thanks for the idea @xenatisch

**Comment by JavierPalaciosNexplore** [comment]
The issue is apparently solved by the [yesterday's release of az-cli](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli). At least `az acr build` started working locally after the upgrade. In our case, we depend on github runners, so I expect it to disappear soon, once they start rolling out machines with updated az-cli.

**Comment by northtyphoon** [comment]
Thanks for reporting it and sorry for the inconvenience.
2.26.1 has been released to address the issue. 
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

**Comment by xenatisch** [comment]
Thanks @northtyphoon, I noticed the release earlier in the day, but it's not been pushed to Azure DevOps machines yet. We haven't been able to deploy anything for nearly 24 hours now.

**Comment by PradeeDevananth** [comment]
az upgrade --yes 
az upgrade is not supported by Cloud Shell.
Not expected these kind of issues from Azure.

**Comment by JotaP** [comment]
Github Action pipelines are also still failing when using their default runners... not good

**Comment by iansong1995** [comment]
This has been brought up in https://github.com/actions/virtual-environments/issues/3735
where they mentioned that they will update the runners by Wed/Thurs...
in the mean time there's a workaround to run az cli upgrade to 2.26.1 (it adds about 5 mins to your workflow)

**Comment by xenatisch** [comment]
Thanks @iansong1995, I can confirm that the workaround works. 

Here it is for anyone who needs it:

```bash
sudo apt-get remove azure-cli

curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

sudo apt-get update

sudo apt-get install azure-cli
```

To be run before the `az acr` command.

@JotaP this is the best we get until next week, apparently.

**Comment by JotaP** [comment]
Yep, we applied this workaround and it actually works (failed to mention it in this thread but did mention here: https://github.com/actions/virtual-environments/issues/3735). Thanks @xenatisch !

**Comment by psinghca** [comment]
@JotaP  Is there any ETA on when the release will be updated on the Cloud Shell as well? It's still running the 2.26.0 version.

**Comment by francesco-scullino** [comment]
any news?

**Comment by wase90168** [comment]
I have just had a look at the Cloud Shell version and for me (West Europe region) it has been updated.
`azure-cli                         2.27.0`

All my build-scripts are working fine as well ^^

**Comment by xenatisch** [comment]
UK South and UK East have been updated too, so I'm closing the issue now.
