### ISSUE TITLE
Azure ml extension ERROR: 'ml' is misspelled or not recognized by the system. when running from Azure DEVOPS with Agent poolself-hosted 

### ISSUE THREAD

**Issue by jguerr06** [Azure/azure-cli#26954]
### Describe the bug

Trying to run the following command:
az ml compute create
From an Azure CLI script in Azure Devops.  Using a self hosted agent pool to a VM we created.  
Installed the latest version of Azure CLI and the latest version of Azure ml extension.
Get the following error:
ERROR: 'ml' is misspelled or not recognized by the system.
2023-07-20T19:53:49.0001918Z 
2023-07-20T19:53:49.0002349Z Examples from AI knowledge base:
2023-07-20T19:53:49.0002666Z az extension add --name anextension
2023-07-20T19:53:49.0003057Z Add extension by name

Have confirmed multiple times that the server (Windows 2019) server has the extension installed correctly.  Opened a Microsoft ticket 
As was referred to here on this issue has stopping us from creating a machine learning compute service.  Please let me know what is needed to resolve this.

### Related command

az ml compute create

### Errors

Get the following error:
ERROR: 'ml' is misspelled or not recognized by the system.
2023-07-20T19:53:49.0001918Z 
2023-07-20T19:53:49.0002349Z Examples from AI knowledge base:
2023-07-20T19:53:49.0002666Z az extension add --name anextension
2023-07-20T19:53:49.0003057Z Add extension by name

### Issue script & Debug output

2023-07-20T20:22:26.6179650Z ERROR: 'ml' is misspelled or not recognized by the system.
2023-07-20T20:22:26.6181023Z 
2023-07-20T20:22:26.6182035Z Examples from AI knowledge base:
2023-07-20T20:22:26.6183140Z az extension add --name anextension
2023-07-20T20:22:26.6184125Z Add extension by name
2023-07-20T20:22:26.6184947Z 
2023-07-20T20:22:26.6185878Z az extension list-available
2023-07-20T20:22:26.6186872Z List all publicly available extensions

### Expected behavior

Expected to run command for create ml compute

### Environment Summary

2023-07-20T20:21:51.2843945Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
2023-07-20T20:21:53.9084006Z azure-cli                         2.50.0
2023-07-20T20:21:53.9085065Z 
2023-07-20T20:21:53.9086144Z core                              2.50.0
2023-07-20T20:21:53.9087120Z telemetry                          1.0.8
2023-07-20T20:21:53.9088185Z 
2023-07-20T20:21:53.9089232Z Extensions:
2023-07-20T20:21:53.9090403Z ml                                2.18.0
2023-07-20T20:21:53.9091146Z 
2023-07-20T20:21:53.9092022Z Dependencies:
2023-07-20T20:21:53.9092942Z msal                              1.22.0
2023-07-20T20:21:53.9093894Z azure-mgmt-resource             23.1.0b2
2023-07-20T20:21:53.9094650Z 
2023-07-20T20:21:53.9095642Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2023-07-20T20:21:53.9096752Z Extensions directory 'C:\Windows\ServiceProfiles\NetworkService\.azure\cliextensions'
2023-07-20T20:21:53.9097629Z 
2023-07-20T20:21:53.9098890Z Python (Windows) 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:05:00) [MSC v.1929 32 bit (Intel)]
2023-07-20T20:21:53.9099856Z 
2023-07-20T20:21:53.9100869Z Legal docs and information: aka.ms/AzureCliLegal
2023-07-20T20:21:53.9101655Z 
2023-07-20T20:21:53.9102306Z 
2023-07-20T20:21:53.9103157Z Your CLI is up-to-date.

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by navba-MSFT** [comment]
@jguerr06 Thanks for reaching out to us and reporting this issue. Could you please run the below command and test ?

> az extension add -n ml --system -y 

If the above step doesn't help, try following [this ](https://stackoverflow.com/a/73969416/17951893)article and check if that helps.

If the note of the above helps, try downgrading the **CLI version azure-cli<2.40.0** That should fix this issue.

**Comment by jguerr06** [comment]
Hey,
   Thanks for the reply.  I tried all the suggestions.  Uninstalled the CLI and downgraded to 2.39 as its right below 2.40.  I then reinstalled the extension with the command provided.  It installed 2.19 version of ml extension.  I then had an error with access to a folder that I resolved. I then restarted the server to be sure.  Now it is back to the same issue as before.  So no change overall.  Followed the article too.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by hunyu** [comment]
@navba-MSFT, do we have any update for @jguerr06? What might be the root cause? and possible work around?

**Comment by jguerr06** [comment]
Hey,
   Issue was not resolved but ran it with ARM template and it worked.  Still looking to find answer for CLI command.

Jose A. Guerrero,
Application Engineering Services (AES) Application Engineer
Application Technical Operations (ATO), MMC Tech
T +1 201 284 3361   M +1 201 716 9351

Marsh McLennan, 445 South St Suite 210, Morristown, NJ, 07960
www.mmc.com<http://www.mmc.com/>
MMC GL ATO AES EPM support (TKT CREATOR) ***@***.******@***.***>
