### ISSUE TITLE
Don't depend on a pre-release

### ISSUE THREAD

**Issue by dhirschfeld** [Azure/azure-cli#31356]
### Describe the bug

https://github.com/Azure/azure-cli/blob/fce4292629f0e02bafda839e4beec7e4c16060f0/src/azure-cli-core/setup.py#L57

### Related command

-

### Errors

Poor form. Prevents packaging in the `conda-forge` ecosystem.

### Issue script & Debug output

-

### Expected behavior

```python
    'msal[broker]>=1.32',
```
https://github.com/AzureAD/microsoft-authentication-library-for-python/releases

### Environment Summary

-

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by dhirschfeld** [comment]
Resolved by #31376

**Comment by ghost** [comment]
Why do you keep comming back to pinning beta versions?

**Comment by dhirschfeld** [comment]
> Why do you keep comming back to pinning beta versions?

💯

It's extremely bad packaging / software engineering practice.

**Comment by kozmaz87** [comment]
Apparently this is something they keep doing over and over and over.  They just released new version and this issue persists.

**Comment by dhirschfeld** [comment]
Reopened to (hopefully) get more visibility since this issue keeps coming up.
