### ISSUE TITLE
az acr login failure

### ISSUE THREAD

**Issue by revodavid** [Azure/azure-cli#4843]
Attempting to log in to a Container Registry server gives me a "stub received bad data" error. (Same thing happens running PowerShell in admin mode.)

```
PS> az acr login --name contregdmsmith
Error saving credentials: error storing credentials - err: exit status 1, out: `The stub received bad data.
```

```
### Environment summary

Install Method: MSI
CLI version: azure-cli (2.0.20)
OS version: Windows 10 (1703 // 15063.674)
Shell Type: Powershell  
```

**Comment by yugangw-msft** [comment]
This is a known issue, see below for the workaround that @djyou provided through a recent email exchange
```
“acr login” uses AAD and docker in Windows uses wincred to save ACR refresh token by default. The token can sometimes exceed 4K in length (e.g., due to customized roles) which will get truncated. You didn’t see it when credential is specified because username/password pair is much shorter.

One quick workaround is to modify <User folder>\.docker\config.json file. Remove the following line so docker will use file system to store tokens:

               "credsStore": "wincred"

We are also rolling out a fix in the token server that will limit the token length.

```

**Comment by djyou** [comment]
@jblackburn21 Do you have a `$HOME/.docker` folder at all?

If you have the folder but not the `config.json` file, you can create the file with content similar to
```
{
	"auths": {
		"MyRegistry.azurecr.io": {
		}
	}
}
```
Or the file will be generated once you have a successful `docker login` or `acr login`.

Adding @shhsu as this is a server side issue and requires further improvement. /cc @sajayantony

**Comment by shhsu** [comment]
@yugangw-msft @revodavid @jblackburn21 @djyou , directly hacking the config.json is not an ideal solution. Please install https://github.com/Azure/acr-docker-credential-helper
This credential helper would help redirect the credentials to the correct stores and without it your login will expire every hour.

**Comment by sajayantony** [comment]
@jblackburn21  - the Credential helper is something that is being worked on and not yet released. @shhsu is working on release it officially since this solves the credential renew issue. 
The main issue is that the token is larger than what windows credential store can handle and hence failing. 
The workaround that @djyou is something that can unblock you and will create a config file that will use the default file credential store instead of the windows credential store. 
```powershell
'{"auths": {"contregdmsmith.azurecr.io": {}}}' | Set-Content $HOME/.docker/config.json
az acr login -n contregdmsmith
```

I think we can consider fixing the CLI to prompt setting the credential store automatically as a fix to this bug.

**Comment by jblackburn21** [comment]
Thanks.  I was able to use the workaround.

**Comment by koolrays** [comment]
Thanks workaround also worked for me.

**Comment by zhang-zedong** [comment]
Thanks. I was also able to use the workaround on mac.

**Comment by sajayantony** [comment]
@StephenWeatherford Is this still failing? The wincred fix has already been merged.

**Comment by StephenWeatherford** [comment]
Well, actually I didn't see it but wasn't sure if it always repros.  I just merged Rutu's code that handles that error.  Hopefully it will never come up.  Thanks!

**Comment by AlphaJuliettOmega** [comment]
Issue is closed but I literally just had to do the work-around to log into ECR

for me the .docker config file had:
```
"credsStore": "Desktop"
```

that line has exactly the same symptoms as
```
"credsStore": "wincred"
```
had...

**Comment by vigouredelaruse** [comment]
> This is a known issue, see below for the workaround that @djyou provided through a recent email exchange
> 
> ```
> “acr login” uses AAD and docker in Windows uses wincred to save ACR refresh token by default. The token can sometimes exceed 4K in length (e.g., due to customized roles) which will get truncated. You didn’t see it when credential is specified because username/password pair is much shorter.
> 
> One quick workaround is to modify <User folder>\.docker\config.json file. Remove the following line so docker will use file system to store tokens:
> 
>                "credsStore": "wincred"
> 
> We are also rolling out a fix in the token server that will limit the token length.
> ```

you can do this on a mac too - it'll probably say "credStore":"desktop"

**Comment by sntgchns** [comment]
works for me, but using Windows 11 with Docker Desktop, should remove `"credsStore": "desktop"` instead `"credsStore": "wincred"`. Thankyou!

**Comment by link049b** [comment]
2026 with Win 11 + WSL still having the same issue (running commands from withing WSL with Docker installed on Win host with WSL integration)!!!!

Nothing worked. Falling back to enabling "Use Admin User" in ACR to be able to login. With admin user credentials everything worked.... no tricky config tweaks.
