### ISSUE TITLE
User update with unsupported ssh public  key fails without error

### ISSUE THREAD

**Issue by kiwi-dejero** [Azure/azure-cli#9780]
## Describe the bug
When --ssh-key-value has an ed25519 key as the first or only entry the command completes as successful.  When there are additional keys in the file after this entry they are not added to authorized_keys

**Command Name**
`az vm user update`

**Errors:**
No Error. Command appears to complete successfully when it has not.

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- Create a file that conatins an ed25519 public key as the first entry, put a supported RSA public key after this.
- `az vm user update -u {} --ssh-key-value {} --ids {}`

## Expected Behavior
When an unsupported public key(ECDSA, RSA <2048bit)  is encountered `az vm` user should error.

## Environment Summary
```
Linux-4.15.0-50-generic-x86_64-with
Python 3.6.4
Shell: bash

azure-cli 2.0.66 *

```
## Additional Context
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-ssh-keys-detailed#supported-ssh-key-formats
https://support.microsoft.com/en-ca/help/4013792/can-t-use-ed25519-ssh-keys-for-azure-linux-vms

**Comment by yonzhan** [comment]
@qwordy add to next Sprint.

**Comment by qwordy** [comment]
Thanks for your feedback. We'll look into it.

**Comment by qwordy** [comment]
@kiwi-dejero It will fail silently in server side if an invalid public key is provided. Azure CLI doesn't check the validity and integrity of the public key. Azure CLI just sends the request to server no matter what public key is given. I can add checks and raise warning in CLI side.
@Drewm3 Do you know anything about this? Is it by design? Can server side add checks for it?

**Comment by Drewm3** [comment]
Let me check with some folks to get some input and then reply back to this thread.

**Comment by yonzhan** [comment]
@Drewm3 Did you have any feedback with this ?

**Comment by qwordy** [comment]
@Drewm3 Is there any update?

**Comment by Drewm3** [comment]
Sorry for the delay on getting a definitive answer on this one. The back end API ownership of this area has moved between developers on the team, and the new owner is coming up to speed on the details. I've pinged them again, and I will update this issue once I have a definitive answer.

**Comment by rgardler** [comment]
I can confirm that this bug has been reproduced. I'll ensure it gets onto the engineering teams backlog and is resolved in due course,

**Comment by yonzhan** [comment]
Can we close this issue or we still need confirm ?

**Comment by yungezz** [comment]
talking with service team on validation.

**Comment by Drewm3** [comment]
@rgardler is going to look into this.

**Comment by rgardler** [comment]
It's been some time since this issue was updated. I'm sorry about that. Unfortunately we don't have any concrete action for this specific issue to report, however I can report on some progress in the space of SSH keys.

As of this month we have deployed a new infrastructure for managing SSH keys. This provides more flexibility in the way we manage and deploy keys. This is a foundational step in a significantly improved SSH experience, across the board. In time this will include our support of other key formats and thus this issue.

**Comment by Drewm3** [comment]
Removing and adding "Feature Request" back to this issue to update the MSFT internal tracking.

**Comment by Drewm3** [comment]
I am going to close this item because the team is not planning to change the server side behavior of silently ignoring invalid keys. However, I suggest that anyone who is interested in supporting ed25519 keys upvote the following item in UserVoice: [ED25519 & ECDSA key format support](https://feedback.azure.com/forums/216843-virtual-machines/suggestions/38924263-ed25519-ecdsa-key-format-support).

**Comment by arcenik** [comment]
The feedback address has changed to https://feedback.azure.com/d365community/idea/1dca6716-dc25-ec11-b6e6-000d3a4f06a4 and marked as completed one year ago.

To be noted that ed25519 now work with VM (azurerm_virtual_machine) but still not with AKS (azurerm_kubernetes_cluster)
